### ISSUE TITLE
Appveyor yarn caching assumes Windows image

### ISSUE THREAD

**Issue by jacobq** [yarnpkg/website#832]
I'm not sure where I should file this issue, but AppVeyor now supports Linux VMs (and supposedly plans to support macOS soon), yet [this page (https://yarnpkg.com/lang/en/docs/install-ci/)](https://yarnpkg.com/lang/en/docs/install-ci/) shows only the `%LOCALAPPDATA%` approach, which will only work on Windows VMs. Looks like `yarn cache dir` shows the corresponding dir on their Linux VMs to be: `/home/appveyor/.cache/yarn/v1` so the following snippet could be added to `appveyor.yml`:

```
for:
-
  matrix:
    except:
      - image: Ubuntu
  cache:
    - "%LOCALAPPDATA%\\Yarn"

-
  matrix:
    only:
      - image: Ubuntu
  cache:
    - "~/.cache/yarn"
```
